/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FSMounter {
  static makeAndMount(mountRoot: string, fsName: string, init: InitOpCB, destroy: DestroyOpCB, lookup: LookupOpCB, forget: ForgetOpCB, getattr: GetAttrOpCB, setattr: SetAttrOpCB, open: OpenOpCB, read: ReadOpCB, release: ReleaseOpCB, opendir: OpenDirOpCB, readdir: ReadDirOpCB, releasedir: ReleaseDirOpCB, getxattr: GetXAttrOpCB, listxattr: ListXAttrOpCB, access: AccessOpCB): FSMounter
  unmount(): void
}
export type JsFSMounter = FSMounter

/** access [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust crate. */
export type AccessOpCB =
  ((err: Error | null, arg0: number, arg1: number) => Promise<number>)

export interface AttrChanges {
  mode?: number
  uid?: number
  gid?: number
  flags?: number
}

export type BufferOrErr =
  | { type: 'Ok', field0: Buffer }
  | { type: 'Err', field0: number }

/**
 * destory [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type DestroyOpCB =
  ((err: Error | null, ) => any)

export interface DirEntry {
  offset: number
  kind: InodeKind
  name: string
}

export type DirListing =
  | { type: 'Lst', field0: Array<DirEntry> }
  | { type: 'Err', field0: number }

export interface FileAttr {
  ino: number
  size: number
  mtime: number
  ctime: number
  btime: number
  kind: InodeKind
  /** Permissions */
  perm: number
  /** User id */
  uid: number
  /** Group id */
  gid: number
  /** Rdev */
  rdev: number
  /** Flags (macOS only, see chflags(2)) */
  flags: number
}

export type FileAttrOrErr =
  | { type: 'Attr', field0: FileAttr }
  | { type: 'Err', field0: number }

/**
 * forget [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 *
 * Arguments:
 * 1. ino
 * 2. nlookup - count of lookups to drop.
 */
export type ForgetOpCB =
  ((err: Error | null, arg0: number, arg1: number) => any)

/**
 * getattr [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 *
 * Arguments:
 * 1. ino
 * 2. fh
 *
 * Should return filesystem error code or an attributes data.
 */
export type GetAttrOpCB =
  ((err: Error | null, arg0: number, arg1?: number | undefined | null) => Promise<FileAttrOrErr>)

/**
 * getxattr [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type GetXAttrOpCB =
  ((err: Error | null, arg0: number, arg1: string, arg2: number) => Promise<XAttrBytesOrErr>)

/** init [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust crate. */
export type InitOpCB =
  ((err: Error | null, arg: number) => any)

export declare const enum InodeKind {
  Directory = 0,
  File = 1,
  SymLink = 2
}

/**
 * listxattr [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type ListXAttrOpCB =
  ((err: Error | null, arg0: number, arg1: number) => Promise<XAttrBytesOrErr>)

/**
 * lookup [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 *
 * Arguments:
 * 1. usual NAPI error. No fs-level error expected here from this module.
 * 2. ino of parent directory, in which lookup is done to see child with given name.
 * 3. child name, which attributes FUSE is requesting.
 *
 * Should return filesystem error code or an attributes data.
 */
export type LookupOpCB =
  ((err: Error | null, arg0: number, arg1: string) => Promise<FileAttrOrErr>)

/**
 * opendir [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type OpenDirOpCB =
  ((err: Error | null, arg0: number, arg1: number) => Promise<ParamsOfOpenedOrErr>)

/** open [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust crate. */
export type OpenOpCB =
  ((err: Error | null, arg0: number, arg1: number) => Promise<ParamsOfOpenedOrErr>)

export interface ParamsOfOpened {
  fh: number
  flags: number
}

export type ParamsOfOpenedOrErr =
  | { type: 'Params', field0: ParamsOfOpened }
  | { type: 'Err', field0: number }

export interface ReadArgs {
  offset: number
  size: number
  flags: number
  lockOwner?: number
}

/**
 * readdir [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type ReadDirOpCB =
  ((err: Error | null, arg0: number, arg1: number, arg2: number) => Promise<DirListing>)

/** read [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust crate. */
export type ReadOpCB =
  ((err: Error | null, arg0: number, arg1: number, arg2: ReadArgs) => Promise<BufferOrErr>)

export interface ReleaseArgs {
  flags: number
  lockOwner?: number
  flush: boolean
}

/**
 * releasedir [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type ReleaseDirOpCB =
  ((err: Error | null, arg0: number, arg1: number, arg2: number) => Promise<undefined>)

/**
 * release [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 */
export type ReleaseOpCB =
  ((err: Error | null, arg0: number, arg1: number, arg2: ReleaseArgs) => Promise<undefined>)

/**
 * setattr [FUSE operation](https://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html) using fuser Rust
 * crate.
 *
 * Arguments:
 * 1. ino
 * 2. fh
 *
 * Should return filesystem error code or updated attributes data.
 */
export type SetAttrOpCB =
  ((err: Error | null, arg0: number, arg1: number | undefined | null, arg2: AttrChanges) => Promise<FileAttrOrErr>)

export type XAttrBytesOrErr =
  | { type: 'Data', field0: Buffer }
  | { type: 'Size', field0: number }
  | { type: 'Err', field0: number }
